"""Shared domain language for media processing and agent state."""

from grounded_video_agent.domain.artifacts import (
    ArtifactKind,
    ArtifactRef,
    ManifestKind,
    ManifestRef,
    ProducerInfo,
    Provenance,
)
from grounded_video_agent.domain.context import TimelineContext
from grounded_video_agent.domain.derivatives import AudioArtifact, VideoClipArtifact
from grounded_video_agent.domain.evidence import (
    CandidateWindow,
    CandidateWindowSet,
    EvidenceAction,
    EvidenceBundle,
    EvidenceClaim,
    EvidenceConflict,
    EvidenceItem,
    EvidenceModality,
    EvidenceScore,
    EvidenceVerificationReport,
    EvidenceVerificationStatus,
    LocalVLMAnalysis,
    RerankingResult,
    RetrievalHit,
    RetrievalResult,
)
from grounded_video_agent.domain.execution import (
    CapabilityError,
    CapabilityRequestContext,
    CapabilityResult,
    CapabilityStatus,
    CapabilityUsage,
    ResourceLimits,
)
from grounded_video_agent.domain.frames import FrameManifest, FrameSamplingStrategy
from grounded_video_agent.domain.indexing import (
    EmbeddingManifest,
    IndexKind,
    IndexManifest,
    IndexModality,
)
from grounded_video_agent.domain.media import (
    AudioStreamInfo,
    ContainerInfo,
    FrameRate,
    MediaProbe,
    SubtitleStreamInfo,
    TimeBase,
    VideoAsset,
    VideoStreamInfo,
)
from grounded_video_agent.domain.ocr import BoundingBox, OCRManifest, OCRObservation, OCRSpan
from grounded_video_agent.domain.segmentation import (
    Chunk,
    ChunkBasis,
    ChunkManifest,
    Shot,
    ShotManifest,
)
from grounded_video_agent.domain.timeline import (
    FrameRef,
    SegmentKind,
    TimelineMapping,
    TimelineSegment,
    TimeRange,
)
from grounded_video_agent.domain.transcript import (
    TranscriptManifest,
    TranscriptSegment,
    TranscriptSource,
    TranscriptWord,
)
from grounded_video_agent.domain.validation import (
    RecoveryAction,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    ValidationStatus,
)
from grounded_video_agent.domain.visual import (
    VisualAnalysisTarget,
    VisualDescription,
    VisualDescriptionManifest,
    VisualDescriptionMode,
)

__all__ = [
    "ArtifactKind",
    "ArtifactRef",
    "AudioArtifact",
    "AudioStreamInfo",
    "BoundingBox",
    "CandidateWindow",
    "CandidateWindowSet",
    "CapabilityError",
    "CapabilityRequestContext",
    "CapabilityResult",
    "CapabilityStatus",
    "CapabilityUsage",
    "Chunk",
    "ChunkBasis",
    "ChunkManifest",
    "ContainerInfo",
    "EmbeddingManifest",
    "EvidenceAction",
    "EvidenceBundle",
    "EvidenceClaim",
    "EvidenceConflict",
    "EvidenceItem",
    "EvidenceModality",
    "EvidenceScore",
    "EvidenceVerificationReport",
    "EvidenceVerificationStatus",
    "FrameRate",
    "FrameManifest",
    "FrameRef",
    "FrameSamplingStrategy",
    "IndexKind",
    "IndexManifest",
    "IndexModality",
    "LocalVLMAnalysis",
    "ManifestKind",
    "ManifestRef",
    "MediaProbe",
    "OCRManifest",
    "OCRObservation",
    "OCRSpan",
    "ProducerInfo",
    "Provenance",
    "RerankingResult",
    "RecoveryAction",
    "ResourceLimits",
    "RetrievalHit",
    "RetrievalResult",
    "SegmentKind",
    "Shot",
    "ShotManifest",
    "SubtitleStreamInfo",
    "TimeBase",
    "TimeRange",
    "TimelineContext",
    "TimelineMapping",
    "TimelineSegment",
    "TranscriptManifest",
    "TranscriptSegment",
    "TranscriptSource",
    "TranscriptWord",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "ValidationStatus",
    "VideoClipArtifact",
    "VideoAsset",
    "VideoStreamInfo",
    "VisualAnalysisTarget",
    "VisualDescription",
    "VisualDescriptionManifest",
    "VisualDescriptionMode",
]
